server:
  port: 8085


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/KFS
    password: admin123
    username: adempiere
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:  org.hibernate.dialect.PostgreSQLDialect

  application:
    name: CURRENCY-CONVERSION-SERVICE